site_name: RARE/freeRtr
site_dir: ../../frederic-loui.github.io/
nav:
  - Home: index.md
  - Getting started:
    - 'Hello freeRtr !': 'guides/getting-started/001-hello-world.md'
    - 'Topology example': 'guides/getting-started/002-topology-example.md'
    - 'Unleash freeRtr !': 'guides/getting-started/003-unleash.md'
    - "Intra domain routing": 'guides/getting-started/004-igp.md'
#  - Reference guides:
#    - 'Routing': 'guides/reference/rout/'
#    - 'MPLS': '/guides/reference/mpls/'
#    - 'QoS': '/guides/reference/qos/'
#  - Validated design:
#    - 'BGP route reflector':
#      - 'Service Provider': '/rvd/sp-bgp-rr/'
#      - 'Kubernetes': '/rvd/k8s-bgp-rr/'
#    - 'MPLS LSR':
#      - 'LDP LSR': '/rvd/mpls-lsr/ldp/'
#      - 'ISIS-SR LSR': '/rvd/mpls-lsr/isis-sr/'
#      - 'OSPF-SR LSR': '/rvd/mpls-lsr/ospf-sr/'
#    - 'MPLS LER':
#      - 'VPNv4/6VPE': '/rvd/mpls-ler/vpnv4-6vpe/'
#      - 'Point to point L2VPN': '/rvd/mpls-ler/p2p-l2vpn/'
#      - 'VPLS': '/rvd/mpls-ler/vpls/'
#      - 'EVPN': '/rvd/mpls-ler/evpn/'
  - License: license.md
  - Contacts: contacts.md
  - About: about.md

theme:
  logo: 'img/rare-icon.png'
  favicon: 'img/favicon.ico'
  name: 'material'
  palette:
    scheme: slate
    primary: 'green'
    accent: 'light green'

extra_css:
  - 'css/extra.css'

extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'

markdown_extensions:
  - pymdownx.highlight:
        linenums: true
  - pymdownx.superfences
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
