site_name: RARE/freeRtr documentation
site_dir: ~/testvojdan/docs.freertr.org/
nav:
  - Home: index.md
  - Getting started:
    - Hello freeRtr !: 'guides/getting-started/001-hello-world.md'
    - Topology example: 'guides/getting-started/002-topology-example.md'
    - Unleash freeRtr !: 'guides/getting-started/003-unleash.md'
    - Intra domain routing: 'guides/getting-started/004-igp.md'
    - MPLS forwarding core: 'guides/getting-started/005-mpls.md'
    - iBGP: 'guides/getting-started/006-ibgp.md'
    - Polka: 'guides/getting-started/007-polka.md'
  - References:
     - All features in one page: 'guides/reference/index.md'
     - Features category: 'guides/reference/tabbed.md'
  - Installation:
    - Overview: 'guides/installation/index.md'
    - Wedge 100BF-32:
      - RARE NOS install: 'guides/installation/wedge100bf32/onie-nos-install.md'
      - Interfaces configuration: 'guides/installation/wedge100bf32/interface.md'
      - Software operation CLI: 'guides/installation/wedge100bf32/rare-nos-lcm-cli.md'
      - RARE NOS update: 'guides/installation/wedge100bf32/rare-nos-upgrade.md'
      - RARE NOS experimental: 'guides/installation/wedge100bf32/rare-nos-exp-upgrade.md'
      - RARE NOS switch profile: 'guides/installation/wedge100bf32/rare-nos-switch-profile.md'
  - Recipes:
      - Basics: 'guides/recipes/basics.md'
      - Bridge and VRF: 'guides/recipes/vrf.md'
  - License: license.md
  - Contacts: contacts.md
  - About: about.md

theme:
  logo: 'img/rare-icon.png'
  favicon: 'img/favicon.ico'
  name: 'material'
  palette:
    scheme: slate
    primary: 'green'
    accent: 'light green'

extra_css:
  - 'css/extra.css'

extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'

markdown_extensions:
  - pymdownx.snippets:
        base_path: ['docs/guides/reference/snippets','.']
        check_paths: true
  - pymdownx.highlight:
        linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
